//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWhRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.check_store_detail = new HashSet<check_store_detail>();
            this.store_material = new HashSet<store_material>();
            this.transaction_detail = new HashSet<transaction_detail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string supplier_infor_id { get; set; }
        public int barcode { get; set; }
        public string type_id { get; set; }
        public string main_unit { get; set; }
        public string change_unit { get; set; }
        public string status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_store_detail> check_store_detail { get; set; }
        public virtual material_type material_type { get; set; }
        public virtual status status { get; set; }
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<store_material> store_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_detail> transaction_detail { get; set; }
    }
}
