//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWhRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_detail
    {
        public int trans_id { get; set; }
        public int material_id { get; set; }
        public long amount { get; set; }
    
        public virtual material material { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
